// ==UserScript==
// @updateURL      https://raw.githubusercontent.com/goldiabroel/techyabroel/main/TechyAbroelSniper.user.js
// @downloadURL    https://raw.githubusercontent.com/goldiabroel/techyabroel/main/TechyAbroelSniper.user.js

// @name         Techy Abroel Sniper Balanced Gold
// @namespace    local.sniper.arb
// @version      56.0
// @match        https://*.payduno.com/*
// @match        https://*.arbpay.*/*
// @match        https://arbpay.*/*
// @match        https://*.payjora.com/*
// @match        https://*.paykexo.com/*
// @match        https://*.payzuva.com/*
// @match        https://*.paykuno.com/*
// @match        https://*.payvuno.com/*
// @match        https://*.paywivo.com/*
// @grant        none
// @run-at       document-idle
// ==/UserScript==

(function () {
    'use strict';

        let running = false;
            let huntTimer = null;
                let refreshing = false;
                    let lastRefresh = 0;
                        let currentMode = 'OTP-UPI';
                            let customChannel = 'OTP-UPI';
                                let isMinimized = false;
                                    let coolDownUntil = 0;

                                        function visible(el) {
                                                return el && el.offsetParent !== null && !el.disabled;
                                                    }

                                                        function text(el) {
                                                                return (el?.innerText || el?.textContent || '').trim();
                                                                    }

                                                                        function tap(el) {
                                                                                if (!visible(el)) return false;
                                                                                        try {
                                                                                                    ['touchstart', 'touchend', 'mousedown', 'mouseup', 'click'].forEach(evt => {
                                                                                                                    el.dispatchEvent(new MouseEvent(evt, {
                                                                                                                                        bubbles: true,
                                                                                                                                                            cancelable: true,
                                                                                                                                                                                view: window
                                                                                                                                                                                                }));
                                                                                                                                                                                                            });
                                                                                                                                                                                                                        return true;
                                                                                                                                                                                                                                } catch (e) {
                                                                                                                                                                                                                                            return false;
                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                            function allVisibleWithText(value) {
                                                                                                                                                                                                                                                                    const wanted = value.toLowerCase();
                                                                                                                                                                                                                                                                            return [
                                                                                                                                                                                                                                                                                        ...document.querySelectorAll(
                                                                                                                                                                                                                                                                                                        'button,div,span,li,a,[role="button"],[role="option"],[role="menuitem"]'
                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                            ].filter(el => {
                                                                                                                                                                                                                                                                                                                                        if (!visible(el)) return false;
                                                                                                                                                                                                                                                                                                                                                    return text(el).toLowerCase() === wanted;
                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                    function makePanel() {
                                                                                                                                                                                                                                                                                                                                                                            if (document.getElementById('arb-master-panel')) return;

                                                                                                                                                                                                                                                                                                                                                                                    const panel = document.createElement('div');
                                                                                                                                                                                                                                                                                                                                                                                            panel.id = 'arb-master-panel';
                                                                                                                                                                                                                                                                                                                                                                                                    panel.innerHTML = `
                                                                                                                                                                                                                                                                                                                                                                                                                <div id="drag-header" style="cursor: move; background: linear-gradient(135deg, #27272a 0%, #18181b 100%); padding: 10px 14px; border-radius: 16px 16px 0 0; display: flex; justify-content: space-between; align-items: center; color: #fff; font-family: sans-serif; user-select: none; border-bottom: 1px solid #3f3f46;">
                                                                                                                                                                                                                                                                                                                                                                                                                                <span id="panel-title" style="font-size: 13px; font-weight: bold; letter-spacing: 1.2px; background: linear-gradient(to bottom, #ffffff, #a1a1aa); -webkit-background-clip: text; -webkit-text-fill-color: transparent;">TECHY ABROEL</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                <button id="btn-minimize" style="background: #3f3f46; border: none; color: #fff; width: 22px; height: 22px; border-radius: 50%; font-size: 14px; cursor: pointer; display: flex; align-items: center; justify-content: center;">−</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div id="panel-body" style="padding: 14px; background: linear-gradient(180deg, #18181b 0%, #09090b 100%); font-size: 12px; color: #fff; display: flex; flex-direction: column; gap: 10px; border-radius: 0 0 16px 16px; box-shadow: 0 10px 30px rgba(0,0,0,0.9);">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div style="color: #a1a1aa; font-size: 11px;">Mode</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div style="display: flex; background: #27272a; padding: 4px; border-radius: 8px; gap: 4px; border: 1px solid #3f3f46;">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button class="mode-btn" data-mode="OTP-UPI" style="flex: 1; padding: 6px; background: #52525b; color: #fff; border: none; border-radius: 6px; font-size: 11px; font-weight: bold; cursor: pointer;">OTP-UPI</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button class="mode-btn" data-mode="BANK" style="flex: 1; padding: 6px; background: transparent; color: #a1a1aa; border: none; border-radius: 6px; font-size: 11px; font-weight: bold; cursor: pointer;">BANK</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button class="mode-btn" data-mode="CUSTOM" style="flex: 1; padding: 6px; background: transparent; color: #a1a1aa; border: none; border-radius: 6px; font-size: 11px; font-weight: bold; cursor: pointer;">CUSTOM</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div id="box-single">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div style="color: #a1a1aa; font-size: 11px; margin-bottom: 4px;">Amount</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <input type="number" id="inp-target" value="100" style="width: 100%; padding: 10px; background: #27272a; color: #fff; border: 1px solid #3f3f46; border-radius: 8px; text-align: center; font-weight: bold; font-size: 16px; box-sizing: border-box;">
                           
